spring:
  application:
    name: account-management
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/amigoscode
    username: amigoscode
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
grpc:
  server:
    port: 6565
    security:
      enabled: true
      key-store: classpath:keystore.p12
      key-store-password: password
      key-store-format: PKCS12


eureka:
  instance:
    nonSecurePort: ${grpc.server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
server:
  port: 8081